# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='date',
            field=models.DateTimeField(max_length=200),
        ),
    ]
