# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_auto_20190522_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('dj', 'Django'), ('ui', 'UI'), ('rest', 'REST API')], max_length=200)),
                ('shifts', multiselectfield.db.fields.MultiSelectField(choices=[('mng', 'Morning'), ('aftn', 'AfterNoon'), ('Eve', 'Evening'), ('night', 'Night')], max_length=200)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Banglore'), ('mum', 'Mumbai'), ('che', 'Chennai')], max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
            ],
        ),
    ]
