# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0004_coursedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseData',
            new_name='CoursesData',
        ),
        migrations.RenameField(
            model_name='coursesdata',
            old_name='trainer_ep',
            new_name='trainer_exp',
        ),
    ]
